# Generated by Django 2.2.7 on 2019-11-18 00:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0042_question_is_visible_to_reviewers'),
        ('event', '0021_auto_20190429_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('years_received_dif_support', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='never', max_length=5), size=None)),
                ('travel_support_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='hotel', max_length=14), size=None)),
                ('speaker_email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difs', to='event.Event')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dif', to='submission.Submission')),
            ],
        ),
    ]
